name: Deploy Angular App to Hostinger

on:
  push:
    branches:
      - main  # Change if you are using different branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print Secret Value
        env:
          MY_SECRET: ${{ secrets.FTP_REMOTE_DIR }}
        run: |
          echo "The secret value for FTP_REMOTE_DIR is: $MY_SECRET"

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build Angular app
        run: npm run build --prod

      - name: 📂 Deploy Genrated Files to Hostinger
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: appdevops.in
          remote-user: ${{ secrets.SSH_USERNAME }}
          private-ssh-key: ${{ secrets.SSH_PRIVATE }}
          source-path: ./www/
          destination-path:  ${{ secrets.FTP_REMOTE_DIR }}
          rsync-options:  --archive --verbose --compress --human-readable --progress --exclude=vendor --exclude=node_modules exclude=.github exclude=.vscode exclude=src