name: Deploy Angular App to Hostinger

on:
  push:
    branches:
      - main  # Change if your branch is different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Setup Node.js
      #run: 'echo "$FTP_REMOTE_DIR" > key'
      # run: echo "Logging FTP_REMOTE_DIR: ${{ secrets.FTP_REMOTE_DIR }}"
      # run: echo "Logging SSH_USERNAME: ${{ secrets.SSH_USERNAME }}"
      # run: echo "Logging SSH_PRIVATE: ${{ secrets.SSH_PRIVATE }}"
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build --prod
        #run: npm run build

      - name: 📂 Deploy Genrated Files to Hostinger
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: appdevops.in
          remote-user: ${{ secrets.SSH_USERNAME }}
          private-ssh-key: ${{ secrets.SSH_PRIVATE }}
          source-path: ./www/
          destination-path:  ${{ secrets.FTP_REMOTE_DIR }}
          rsync-options:  --archive --verbose --compress --human-readable --progress --exclude=vendor --exclude=node_modules exclude=.github exclude=.vscode exclude=src